### ISSUE TITLE
PCE not calculated correctly

### ISSUE THREAD

**Issue by rbrenesh** [mutovis/analysis-software#8]
Attached is a picture of the reported PCEs for some devices. While Pmax is correct, the number reported in both the ssPCE and PCE fields are not correct. Not sure where the discrepancy is coming from. 

![Screenshot from 2019-03-13 14-39-49](https://user-images.githubusercontent.com/33428877/54322512-da9e5d00-45cb-11e9-81a9-18541f6a1767.png)

![Screenshot from 2019-03-13 14-40-22](https://user-images.githubusercontent.com/33428877/54322517-e0943e00-45cb-11e9-9acf-8693a73afe71.png)

**Comment by greyltc** [comment]
The PCE actually looks alright considering the data file says the device is getting 6-700 suns ;-)
The problem is likely with the intensity measurement/calibration.

PCE is just the P_max scaled by number of suns. Your suns column is clearly wrong.

The suns column is calculated from the number of ADC counts I get from the reference diode circuit at the start of the run divided by the number of counts I got when you ran the measurement program with `--calibrate-diodes`.

Try recalibrating the diodes. There's a chance I'm doing something dumb like making the reference diode reading before turning the light on or something. I'll check on that...

**Comment by greyltc** [comment]
At first glance, I don't see anything terribly wrong in the code with the diode intensity measurement. Looks like I turn the light on, wait half a second, then read the diode ADC values.

**Comment by rbrenesh** [comment]
Just recalibrated the cells and it's looking all good. I think I must have recalibrated them by accident with the lights off or something.
